### ISSUE TITLE
Android Q redirectUserToSignIn(...) not opening browser

### ISSUE THREAD

**Issue by igorkos** [blockstack/blockstack-android#164]
After update to Android Q call of redirectUserToSignIn not launching  Mobile web browser. I tried on multiple devices same behavior works on Android 7, 8 fails on 9(Q)

Log from device:
SessionStore: set session data in store {"transitKey":"......"}
LogConsole: [INFO] blockstack.js: generating v1.3.1 auth request
LogConsole: [INFO] detected mobile OS, sending to https

**Comment by friedger** [comment]
I am running apps on Android 9 successfully. This issue is about Android 10 (Q).

**Comment by friedger** [comment]
@igorkos I could successfully login on helloblockstack.com. Could you please provide more details?

**Comment by igorkos** [comment]
I only see provided log  lines. I ruined to this issue on 2 devices they was running Android 8. On both I successfully logged  and receiving call back. On some moment upgrade to android Q happened after upgrade my application was running fine up to moment when I sign out. After signing out I can't invoke browser to proceed with new signing.

**Comment by friedger** [comment]
@igorkos If you uninstall the app and reinstall, does that solve the problem? Do you think the problem is with the browser or with the Android app?

**Comment by igorkos** [comment]
Process: com.kosulin.photo_boost, PID: 31020
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:937)
        at android.app.ContextImpl.startActivity(ContextImpl.java:913)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at org.blockstack.android.sdk.BlockstackSession$JSAndroidBridge$setLocation$1.invoke(BlockstackSession.kt:1042)
        at org.blockstack.android.sdk.BlockstackSession$JSAndroidBridge$setLocation$1.invoke(BlockstackSession.kt:813)

**Comment by igorkos** [comment]
Modifying BlockstackSession.kt line 1043 to fixed problem
                   it.startActivity(Intent(Intent.ACTION_VIEW, locationUri).addCategory(Intent.CATEGORY_BROWSABLE).**addFlags(FLAG_ACTIVITY_NEW_TASK)**)

**Comment by friedger** [comment]
I don't think that is the right solution here. 
@igorkos It looks to me that your call needs to made from a different context. 
Could you please share some more information when this error happens? Does it happen when you call `redirectUserToSignIn`? How do you call that method?

Furthermore, we have a new version in beta that reduces the size of the SDK by 60+%. Have you tried https://jitpack.io/#blockstack/blockstack-android/9884ffb ?

**Comment by friedger** [comment]
@igorkos Could you please verify with version 0.5.0 of the SDK?

**Comment by friedger** [comment]
I am closing this due to inactivity. @igorkos Please open a new issue if you still see problems with the redirect.
