### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by FrankyHo** [blockstack/blockstack-android#173]
after enable minify and generate apk of "/example" tutorial, app crash 

> A/art: art/runtime/thread.cc:1105] No pending exception expected: ### java.lang.ClassNotFoundException: Didn't find class "com.eclipsesource.v8.V8Object" on path: DexPathList[[zip file "/data/app/org.blockstack.android.sample-2/base.apk"],nativeLibraryDirectories=[/data/app/org.blockstack.android.sample-2/lib/arm, /vendor/lib, /system/lib]]

Then I modify proguard-rules.pro `-keep class com.eclipsesource.v8.** { *; }` ,then I got another crash

> 12-16 18:17:37.982 22157-22157/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.blockstack.android.sample, PID: 22157
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.blockstack.android.sample/org.blockstack.android.MainActivity}: java.lang.IllegalStateException: java.lang.NoSuchMethodException: log [class java.lang.String]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2889)
        at android.app.ActivityThread.access$900(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6219)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: log [class java.lang.String]
        at com.eclipsesource.v8.V8Object.registerJavaMethod()
        at com.eclipsesource.v8.V8Object.registerJavaMethod()
        at org.blockstack.android.b.e.d()
        at org.blockstack.android.b.e.<init>()
        at org.blockstack.android.b.e.<init>()
        at org.blockstack.android.MainActivity.onCreate()
        at android.app.Activity.performCreate(Activity.java:6374)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2763)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2889) 
        at android.app.ActivityThread.access$900(ActivityThread.java:181) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6219) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 

Is any any instruction of proguard rules? thanks for help

**Comment by friedger** [comment]
With version 0.5.0 this shouldn't be a problem.

Franky Ho <notifications@github.com> schrieb am Mo., 16. Dez. 2019, 12:07:

**Comment by FrankyHo** [comment]
Thank you, it works. BTW I am using blockstack-react-native but seems only support in version 0.4.6. Hope can upgrade soon.

**Comment by friedger** [comment]
@FrankyHo In the context of https://github.com/blockstack/blockstack-react-native/issues/26 the android SDK will be upgraded to 0.5.0.... work in progress.
