### ISSUE TITLE
loadUserData throws exception if not logged in

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#38]
When loadUserData is called before the user is logged in the following exception is thrown:

```
Caused by: org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:160)
        at org.json.JSONObject.<init>(JSONObject.java:173)
        at org.blockstack.android.sdk.BlockstackSession$loadUserData$1.onReceiveValue(BlockstackSession.kt:104)
```

**Comment by friedger** [comment]
This is due to the js method returning JSON.NULL which is converted to the string "null" that can't be parsed in the android method

**Comment by larrysalibra** [comment]
Fixed thanks to @friedger 's pull request.
