### ISSUE TITLE
[duktape] encryptContent does not work

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#95]
Following #92 `encryptContent` does not work

     Caused by: com.squareup.duktape.DuktapeException: TypeError: cannot read property 'getBytes' of null
        at com.squareup.duktape.Duktape.call(Native Method)
        at com.squareup.duktape.Duktape.access$100(Duktape.java:26)
        at com.squareup.duktape.Duktape$1.invoke(Duktape.java:132)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy1.encryptContent(Unknown Source)
        at org.blockstack.android.sdk.BlockstackSession2.encryptContent(BlockstackSession2.kt:227)
        at org.blockstack.android.CipherActivity.encryptDecryptString(CipherActivity.kt:72)
        at org.blockstack.android.CipherActivity.checkLogin(CipherActivity.kt:44)

Steps to reproduce:

1. Checkout branch `feature/duktape`
1. In `CipherActivity.checkLogin` uncomment `encryptDecryptString`, comment out `putFileGetFile`
1. Run example-multi-activity
1. Sign-in with blockstack
1. You should be redirected to CipherActivity
1. Ignore the screen and that the app crashed
1. See the log

The error is thrown in `Rand` in blockstack.js

**Comment by friedger** [comment]
If you replace `this.rand.getBytes` in the if condition of `Rand.prototype._rand=function _rand(n)` by 
`this.rand && this.rand.getBytes` then duktape passes there and fails when calling `this.rand.getByte` (without s) shortly after.

To me it is not clear how to define `Rand`, `rand()` and/or `_rand()` in blockstack.js or blockstack_android2.js

**Comment by friedger** [comment]
In blockstack.js
* replace `Rand.prototype.generate` function definition with

      Rand.prototype.generate=function generate(len){return global.generate(len);};

In blockstack_android2.js
* add

      getByte = function() {
        return 1; // TODO use real random
      }
      global.generate=function (len) {
          var res=new Uint8Array(len);for(var i=0;i<res.length;i++){res[i]=getByte();}
          return res;
      }

**Comment by larrysalibra** [comment]
Awesome that you figured this out!
